image: Visual Studio 2019

shallow_clone: true

platform:
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc17/
    - appveyor.yml
    - cmake/

install:
  - cmd : vcpkg install boost-iostreams:x64-windows
  - cmd : vcpkg install boost-asio:x64-windows
  - cmd : vcpkg install boost-system:x64-windows
  - cmd : vcpkg install boost-filesystem:x64-windows
  - cmd : vcpkg install boost-variant:x64-windows
  - cmd : vcpkg install boost-lockfree:x64-windows
  - cmd : vcpkg install cryptopp:x64-windows
  - cmd : vcpkg install fmt:x64-windows
  - cmd : vcpkg install luajit:x64-windows
  - cmd : vcpkg install --recurse libmariadb:x64-windows
  - cmd : vcpkg install pugixml:x64-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

after_build:
  - 7z a -tzip tfs.zip -r .\vc17\*.exe -ir!.\vc17\*.dll
  
artifacts:
  - path: vc17\**\theforgottenserver*.exe
  - path: vc17\**\*.dll
  - path: tfs.zip